server:
  port: 8083

spring:
  application:
    name: vehicle-service

  config:
    import: "optional:configserver:"

  datasource:
    url: jdbc:mysql://localhost:3306/Vehicle_service_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Ijse@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


